# version: "3.9"

services:
  postgres:
    image: postgres:16

    container_name: lapangin-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: lapangin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    # ports:
    #   - "5432:5432"  # Tidak expose ke publik — app akses via internal network

    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .

    container_name: lapangin-app

    depends_on:
      - postgres

    env_file:
      - .env.local

    ports:
      - "3000:3000"

volumes:
  postgres_data:
